# Generated by Django 3.2.9 on 2021-11-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorias', '0003_categoria'),
        ('blog_posts', '0005_alter_post_excerto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria_post',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_categorias.categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_post',
            field=models.ImageField(default=1, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
